Monkey Finances/Models/ErrorViewModel.cs
namespace Monkey_Finances.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Monkey Finances/Models/LoginModel.cs
namespace Monkey_Finances.Models
{
    public class LoginModel
    {
        public string Email { get; set; }

        public string Senha { get; set; }
    }
}

Monkey Finances/Models/RegistroModel.cs
namespace Monkey_Finances.Models
{
    public class RegistroModel
    {
        public int Id { get; set; }

        public string? Name { get; set; }

        public double? Valor { get; set; }

        public string? Tipo { get; set; }
    }
}

Monkey Finances/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Monkey_Finances.Models;

namespace Monkey_Finances.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Monkey Finances/Controllers/LoginController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Monkey_Finances.Models;

namespace Monkey_Finances.Controllers
{
    public class LoginController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Entrar(LoginModel loginModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (loginModel.Email == "asd@asd" && loginModel.Senha == "123")
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    TempData["MensagemErro"] = $"email ou senha inválidos";

                }

                return View("Index");
            }
            catch (System.Exception)
            {
                TempData["MensagemErro"] = $"erro ao logar";
                throw;
            }
        }
    }
}

Monkey Finances/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Monkey_Finances.Models;
using Monkey_Finances.Repositorio;

namespace Monkey_Finances.Controllers
{
    public class RegistroController : Controller
    {
        private readonly IRegistroRepositorio _registroRepositorio;

        public RegistroController(IRegistroRepositorio registroRepositorio)
        {
            _registroRepositorio = registroRepositorio;
        }

        public IActionResult Index()
        {
            List<RegistroModel> registro = _registroRepositorio.BuscarTodos();
            return View(registro);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            RegistroModel registro = _registroRepositorio.ListarPorId(id);
            return View(registro);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            RegistroModel registro = _registroRepositorio.ListarPorId(id);
            return View(registro);
        }
        
        public IActionResult Apagar(int id)
        {
            _registroRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(RegistroModel registro)
        {
            _registroRepositorio.Adicionar(registro);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar(RegistroModel registro)
        {
            _registroRepositorio.Atualizar(registro);

            return RedirectToAction("Index");
        }


    }
}

Monkey Finances/Views/Dashboard/Index.cshtml
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">first</th>
      <th scope="col">last</th>
      <th scope="col">handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>jacob</td>
      <td>fat</td>
      <td>lingard</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>brenno</td>
      <td>santos</td>
      <td>oliveira</td>
    </tr>
  </tbody>
</table>

Monkey Finances/Views/Home/ApagarConfirmacao.cshtml
@model RegistroModel
@{
    ViewData["Title"] = "Confirmar apagar o registro";
}

<div class="text-center">
    <h3>Realmente deseja apgar o Registro (@Model.Name)?</h3>
</div>


<a class="btn btn-primary w-100" asp-action="Index" asp-controller="Registro" role="button">Cancelar exclusão</a>
<br />
<br />
<a class="btn btn-danger w-100" asp-action="Apagar" asp-controller="Registro" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>

Monkey Finances/Views/Home/Criar.cshtml
@model RegistroModel
@{
    ViewData["Title"] = "Cadastrar Registro";
}

<div class="text-center">
    <h1 class="display-4">Criar Registro</h1>
</div>

<form asp-controller="Registro" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Digite o nome do item">
    </div>

    <br />

    <div class="form-group">
        <label for="valor" class="form-label">Valor</label>
        <input type="text" asp-for="Valor" class="form-control" placeholder="Digite o valor do item">
    </div>

    <br />

    <div class="form-group">
        <label for="tipo" class="form-label">Tipo</label>
        <input type="text" asp-for="Tipo" class="form-control" placeholder="Digite o tipo do item">
    </div>

    <br />
    <br />

    <button type="submit" class="btn btn-primary w-100">Adicionar</button>
    <br />
    <br />
    <a class="btn btn-secondary w-100" asp-controller="Registro" asp-action="Index" role="button">Voltar</a>
</form> 

Monkey Finances/Views/Home/Editar.cshtml
@model RegistroModel
@{
    ViewData["Title"] = "Editar Registro";
}

<div class="text-center">
    <h1 class="display-4">Editar Registro</h1>
</div>

<form asp-controller="Registro" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Digite o nome do item">
    </div>

    <br />

    <div class="form-group">
        <label for="valor" class="form-label">Valor</label>
        <input type="text" asp-for="Valor" class="form-control" placeholder="Digite o valor do item">
    </div>

    <br />

    <div class="form-group">
        <label for="tipo" class="form-label">Tipo</label>
        <input type="text" asp-for="Tipo" class="form-control" placeholder="Digite o tipo do item">
    </div>

    <br />
    <br />

    <button type="submit" class="btn btn-primary w-100">Alterar</button>
    <br />
    <br />
    <a class="btn btn-secondary w-100" asp-controller="Registro" asp-action="Index" role="button">Voltar</a>
 
</form>

Monkey Finances/Views/Home/Index.cshtml
<nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="relative flex h-16 items-center justify-between">
            <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
                <!-- Mobile menu button-->
                <button id="btn-toogle-menu" type="button" onclick="hiddenMenu()"
                        class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                        aria-controls="mobile-menu" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <!--
                      Icon when menu is closed.

                      Heroicon name: outline/bars-3

                      Menu open: "hidden", Menu closed: "block"
                    -->
                    <div id="showIcon" class="blockMenu">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                             stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                        </svg>
                    </div>
                    <!--
                      Icon when menu is open.

                      Heroicon name: outline/x-mark

                      Menu open: "block", Menu closed: "hidden"
                    -->
                    <div id="hiddenIcon1" class="hiddenMenu">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                             stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </div>
                </button>
            </div>
            <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-between">
                <div class="flex flex-shrink-0 items-center">
                    <img class="h-10 mr-1" src="~/images/semFundoMacacoBranco.png" alt="logo">
                   
                </div>
                <div class="hidden sm:ml-6 sm:block">
                    <div class="flex space-x-4">
                        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                        <a href="#" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium"
                           aria-current="page">Registros</a>

                        <a href="#"
                           class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Team</a>

                        <a href="#"
                           class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Projects</a>

                        <a href="#"
                           class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Calendar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="sm:hidden" id="mobile-menu">
        <div class="hiddenMenuMaior" id="hiddenIcon2">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="#" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium"
               aria-current="page">Registros</a>

            <a href="#"
               class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Team</a>

            <a href="#"
               class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Projects</a>

            <a href="#"
               class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Calendar</a>
        </div>
    </div>
</nav>
<div class="flex flex-col">
  <div class="overflow-hidden sm:-mx-6 lg:-mx-6">
    <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden d-flex justify-content-center" style="display: flex; justify-content: center">
        <table class="w-2/4 text-center">
          <thead class="border-b bg-gray-50">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">
                .
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">
                Nome do item
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">
                Valor
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4">
                Handle
              </th>
            </tr>
          </thead class="border-b">
          <tbody>
            <tr class="bg-white border-b">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">1</td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                Aposta
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                100
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                mdo
              </td>
            </tr class="bg-white border-b">
            <tr class="bg-white border-b">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">2</td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                Computador
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                500
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                fat
              </td>
            </tr>
            <tr class="bg-white border-b">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">3</td>
       <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                twitter
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                twitter
              </td>
               <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                fat
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<style>
    .hiddenMenu {
        display: none;
        height: 1.5rem;
        width: 1.5rem;
    }

    .hiddenMenuMaior {
        display: none;
        margin-top: 0.25rem;
        padding-left: 0.5rem;
        padding-right: 0.5rem;
        padding-top: 0.5rem;
        padding-bottom: 0.75rem;
    }

    .blockMenuMaior {
        display: block;
        margin-top: 0.25rem;
        padding-left: 0.5rem;
        padding-right: 0.5rem;
        padding-top: 0.5rem;
        padding-bottom: 0.75rem;
    }

    .blockMenu {
        display: block;
        height: 1.5rem;
        width: 1.5rem;
    }
</style>

<script>
    var showIcon = document.getElementById("showIcon");
var hiddenIcon1 = document.getElementById("hiddenIcon1");
var hiddenIcon2 = document.getElementById("hiddenIcon2");

function hiddenMenu() {
    hiddenIcon2.className == "hiddenMenuMaior"
        ? (hiddenIcon2.className = "blockMenuMaior")
        : (hiddenIcon2.className = "hiddenMenuMaior");

    showIcon.className == "blockMenu"
        ? (showIcon.className = "hiddenMenu")
        : (showIcon.className = "blockMenu");

    hiddenIcon1.className == "hiddenMenu"
        ? (hiddenIcon1.className = "blockMenu")
        : (hiddenIcon1.className = "hiddenMenu");
}
</script>

Monkey Finances/Views/Login/Index.cshtml
@model LoginModel

<section class="bg-gray-900 dark:bg-gray-900 h-screen">
    <div class="flex flex-col items-center justify-center px-6 mx-auto h-screen lg:py-0">
        <a href="#" class="no-underline flex items-center mb-6 text-2xl font-semibold text-white">
            <img class="h-12 mr-1" src="~/images/semFundoMacacoBranco.png" alt="logo">
            Monkey Finances
        </a>
        <div class="w-full bg-white rounded-lg shadow border md:mt-0 sm:max-w-md xl:p-0 bg-gray-800 border-gray-700">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl text-center font-bold leading-tight tracking-tight  md:text-2xl text-white">
                    Entre com a sua conta
                </h1>

                @if (TempData["MensagemErro"] != null)
                {
                    <div class="alert alert-danger" role="alert">
                        <button font-color="red" type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
                        @TempData["MensagemErro"]
                    </div>
                }

                <form asp-controller="Login" asp-action="Entrar" method="post" class="space-y-4 md:space-y-6 mr-4">
                    <div>
                        <label for="Email" class="block mb-2 text-sm font-medium text-white">Email</label>
                        <input type="Email" asp-for="Email" name="Email" id="Email" class="border-none border sm:text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" placeholder="nome@exemplo.com" required="">
                    </div>
                    <div>
                        <label for="Senha" class="block mb-2 text-sm font-medium text-white">Senha</label>
                        <input type="password" asp-for="Senha" name="Senha" id="Senha" placeholder="••••••••" class="border-none border sm:text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" required="">
                    </div>
                    <div class="flex items-center justify-between">
                        <div class="flex items-start">
                            <div class="flex items-center h-5">
                                <input id="remember" aria-describedby="remember" type="checkbox" class="cursor-pointer w-4 h-4 border rounded 50 focus:ring-3 bg-gray-700 border-gray-600 focus:ring-primary-600 ring-offset-gray-800" required="">
                            </div>
                            <div class="ml-3 text-sm">
                                <label for="remember" class="text-gray-300">Lembrar de mim?</label>
                            </div>
                        </div>
                        <a href="#" class="text-sm font-medium no-underline text-primary-500 hover:text-primary-700">Esqueceu senha?</a>
                    </div>
                    <button type="submit"
                            class="my-2 ml-2 cursor-pointer border-none w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                        Entrar
                    </button>
                    <p class="text-sm text-center font-light text-gray-400">
                        Ainda não tem uma conta? <a onclick="location.href='@Url.Action("Index", "Register")'" class="no-underline cursor-pointer font-medium text-primary-500 hover:text-primary-700">Cadastre-se</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>

Monkey Finances/Views/Register/Index.cshtml
<section class="bg-gray-50 dark:bg-gray-900 h-screen">
    <div class="flex flex-col items-center justify-center px-6 mx-auto h-screen lg:py-0">
        <a href="#" class="no-underline flex items-center mb-6 text-2xl font-semibold text-white">
            <img class="h-12 mr-1" src="~/images/semFundoMacacoBranco.png" alt="logo">
            Monkey Finances
        </a>
        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl text-center font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                    Crie sua conta
                </h1>
                <form class="space-y-4 md:space-y-6 mr-4" action="#">
                    <div>
                        <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Seu email</label>
                        <input type="email" name="email" id="email" class="border-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="nome@exemplo.com" required="">
                    </div>
                    <div>
                        <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Senha</label>
                        <input type="password" name="password" id="password" placeholder="••••••••" class="border-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                    </div>
                    <div>
                        <label for="confirm-password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirmar Senha</label>
                        <input type="confirm-password" name="confirm-password" id="confirm-password" placeholder="••••••••" class="border-none bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                    </div>
                    <button 
                        type="submit" 
                        class="my-2 ml-2 cursor-pointer border-none w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                        Criar conta
                    </button>
                    <p class="text-center text-sm font-light text-gray-500 dark:text-gray-400">
                        Já possui uma conta? <a onclick="location.href='@Url.Action("Index", "Login")'" class="cursor-pointer no-underline font-medium text-primary-600 hover:underline dark:text-primary-500">Entre aqui</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>

Monkey Finances/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Monkey Finances</title>
    <link rel="stylesheet" href="~/css/app.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/app.min.css" asp-append-version="true" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css"
          integrity="sha256-x8PYmLKD83R9T/sYmJn1j3is/chhJdySyhet/JuHnfY=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://kit.fontawesome.com/115ac8d491.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/flowbite@1.5.3/dist/flowbite.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>

</head>
<body style="background-color: #111827">
 
    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>